### ISSUE TITLE
Error when component name includes hyphen "-"

### ISSUE THREAD

**Issue by Nikhil-Vats** [biojs/generator-biojs-webcomponents#5]
The Yeoman generator shows no instruction to not include the hyphen in component's name but it shows an error if we include a hyphen. 
Example - If I enter "my-biojs-component" as a component's name, the yeoman generator will show error.
![image](https://user-images.githubusercontent.com/31413407/55674632-bd139900-58d4-11e9-949a-80f05baeb1af.png)
The image below shows that no instruction is shown to the user to not include the hyphen in the name.
![image](https://user-images.githubusercontent.com/31413407/55674634-d1f02c80-58d4-11e9-914e-dccebfee2bc5.png)

**Comment by yochannah** [comment]
Whoops - good spot! We need to fix this. :+1:
