### ISSUE TITLE
Generator automatically converts small letters to capital letters in component's name.

### ISSUE THREAD

**Issue by Nikhil-Vats** [biojs/generator-biojs-webcomponents#6]
If we write "myComponent" as the name, it will convert it to "MyComponent".
![image](https://user-images.githubusercontent.com/31413407/55674693-94d86a00-58d5-11e9-8e91-0bebe2df555b.png)
Also, the user should be allowed to enter his own full name and it should not be succeeded with "BioJSComponent".

**Comment by awasthishubh** [comment]
If I am not getting wrong, problem here is that it allows special characters in name. It can be fixed with a simple regex replace.
